FROM wordpress:latest

ENV WORDPRESS_DB_HOST='db'
ENV WORDPRESS_DB_USER='exampleuser'
ENV WORDPRESS_DB_PASSWORD='examplepass'
ENV WORDPRESS_DB_NAME='exampledb'
ENV WORDPRESS_AUTH_KEY='R8q+z:JHAHYnf(4MUjf#=Rmt_+j3LiP0~8/WcArwF++a?}G_T&%qsBRq4ES0g*Sc'
ENV WORDPRESS_SECURE_AUTH_KEY='Q^F(H^Ehe66&n+jLV+-adg2i|Bf[4+zd)lMi+Q,GqNqcvKCS/fcrz%a,u+Ec.kUw'
ENV WORDPRESS_LOGGED_IN_KEY='vGP52XL:OLg9!k&0DytN2Vsdwv{Yv=KV8!|0kfMh1w1/a+`<Exb9+`*sXwJ-igeY'
ENV WORDPRESS_NONCE_KEY='YQ^LG,l5_{NWrWA{;jV=V}}/>d?>kt|eIs--8IlH~r?xg>5vG2v>|ZK{@i/<$Ob{'
ENV WORDPRESS_AUTH_SALT='ts0wJ}m9I-6AxC@>cv_&nbW:~,5lS!(tMJ4[s98FE3T+:+--fR+0qBT+&)s~imYE'
ENV WORDPRESS_SECURE_AUTH_SALT='3(%S;h?ik9;?{iW%_.0}wfF0g+OPK(O/qIx2S4W Dcw./P&[WxyAWD5h8Z4wd9O;'
ENV WORDPRESS_LOGGED_IN_SALT='ku)rJ{9S|*P+$}XrPF_L9M<.TbQPc%!Nl]My?8#u./B%D&6lZ|JevHg>coSxqIDg'
ENV WORDPRESS_NONCE_SALT='R|!q4~+:0RE%_#r8l`Kcs`6<Q8#dg6{h[U>M],c*nq&)d10J||o)]CP?A7p-Ezg='
